### ISSUE TITLE
Log Error on invalid JSON

### ISSUE THREAD

**Issue by mkly** [kylewelsby/angular-post-message#12]
Hello,
Thanks for taking the time to create this great library.

https://github.com/kylewelsby/angular-post-message/blob/master/src/angular-post-message.js#L26-L32

In this we `$log.error()` if the message is not valid JSON. I'm not sure it is guaranteed that all messages in the system will always fall within this convention. Would an excepted pull request allow for disabling this error logging? Right now I can decorate the `$log.error()` method to avoid this so there is a work around, but felt this may not be the desired behavior for all users.

**Comment by kylewelsby** [comment]
You're right, this `$log.error` was purely for debugging. The log could simply be removed.
