### ISSUE TITLE
Latest version (1.4) is not available through bower/npm

### ISSUE THREAD

**Issue by Mando-Chris** [kylewelsby/angular-post-message#14]
Thanks for the useful module!  We need the fix added in 1.4, but 1.3.1 is the version that gets pulled down by bower.

We are using our own version for now, but would love to go back onto your release build.

**Comment by kylewelsby** [comment]
sorry about that, its likely i forgotten to push a tagged release. I shall do that now.

**Comment by kylewelsby** [comment]
thanks for letting me know, that has been pushed now.   sorry for the inconvenience   https://github.com/kylewelsby/angular-post-message/releases/tag/v1.4.0
