### ISSUE TITLE
Bower Main Should Point At Non-Minified Version

### ISSUE THREAD

**Issue by mtpultz** [kylewelsby/angular-post-message#15]
Bower main is for automated tooling and shouldn't be the minified version since the tooling is typically set on --production to minify all dependencies, but as is the minified file will be reminified.

**Comment by mtpultz** [comment]
I updated bower.json and pushed a PR #16

**Comment by mtpultz** [comment]
Thanks @kylewelsby.  Any chance of a minor version bump so the merge is available off master?

**Comment by mtpultz** [comment]
Hi @kylewelsby sorry to bug you. Is it possible to cut a minor release that includes these changes so we don't have to work off master in case of any breaking changes introduced during development.

**Comment by kylewelsby** [comment]
there we go.   😄
