### ISSUE TITLE
Question: Fire message from Angular to html

### ISSUE THREAD

**Issue by jwright04** [kylewelsby/angular-post-message#8]
Hello, 

I'm trying to do the opposite of what you have going on in your example, I was trying to call a function on my html page from my angular controller and I was hoping for a little clarification.  I'm using your example here:

```
$scope.sendMessage = function (){
   console.log("SENDING MESSAGE");
    $scope.$emit(
      '$messageOutgoing',
      angular.toJson({"response":"hi"})
    );
  };
$scope.sendMessage();
```

and in my html, I would like to do something like:

```
...
</html>
<script type="text/javascript">
  function sendMessage() {
   console.log("RECEIVING MESSAGE");
  };
</script>
```

I kept the method names the same for better clarification, but i'd like to get the `RECEIVING MESSAGE` log.  Can you provide a little clarification?

**Comment by kylewelsby** [comment]
Hi @jwright04 I have no problem in asking your question.

So, you're wanting to emit a message from your angular.js application to a native javascript listener.

You could do something like this:

```
// angular app
var app = angular.module('app',['ngPostMessage']);
app.controller('MainCtrl', function($scope) {
  $scope.sendMessage = function (){
    $scope.$emit(
      '$messageOutgoing',
      angular.toJson({"response":"hi"})
    );
  };

$scope.sendMessage();
});
```

In your receiving native JavaScript app you would have something like:

```
  window.onmessage = function(e){
    if(e.origin === window.location.origin){
      return;
    }
    if(!e.data){
      throw new Error('Message event contains no readable data.');
    }
    console.log(e.data);
    var elm = document.createElement('li');
    elm.innerHTML = e.data;
    var out = document.getElementById('messages');
    out.appendChild(elm);
  }
```

if your wanting to receive a message into your angular.js app from a native JavaScript app, you could do something like this.

```
// native app
function sendMessage() {
    window.parent.postMessage(
      JSON.stringify({"greeting": "hello world"}), // A string type message to send.
      "*" // The intended origin, in this example we use the any origin wildcard.
    );
  }
sendMessage();
```

```
// angular app
var app = angular.module('app',['ngPostMessage']);
app.controller('MainCtrl', function($scope) {
  $scope.messages = [];
  $scope.$root.$on('$messageIncoming', function (event, data){
    console.log(data);
  });
});
```

The example in [README](https://github.com/kylewelsby/angular-post-message/blob/master/README.md) is linked to a live [gist](https://gist.github.com/kylewelsby/585b3a5395c6731acc50) that should ping a message to and from the angular application.

Hope this helps your application.

Kyle

**Comment by jwright04** [comment]
Thanks for the response, i guess where I'm getting hung up is, where is `function sendMessage(){}...` on the native javascript side? Because ultimately, I want to do something in that method when it is fired from angular.

**Comment by kylewelsby** [comment]
in the angular post-message module, the event `$messageIncoming` acts a lot like `window.onmessage`. 

It just cleans and sanitises the incoming data. [Core logic here](https://github.com/kylewelsby/angular-post-message/blob/master/src/angular-post-message.js#L20-L36)

Mozilla has fantastic documentation on how [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) works and its available API's

Hope this helps.
